---
efiSystemPartition: "/boot/efi"
userSwapChoices:
  - none
  - small
  - suspend
  - file
drawNestedPartitions: true
defaultFileSystemType: "ext4"
availableFileSystemTypes:
  - "ext4"
  - "btrfs"
  - "xfs"
enableLuksAutomatedPartitioning: true
