---
defaultGroups:
  - wheel
  - video
  - audio
  - input
  - storage
  - lp
autologinGroup: autologin
doAutologin: false
sudoersGroup: wheel
setRootPassword: true
doReusePassword: false
allowWeakPasswords: false
allowWeakPasswordsDefault: false
userShell: /usr/bin/zsh
